Style/CaseIndentation:
  IndentOneStep: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%r": "()"
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/Alias:
  Enabled: false
Metrics/LineLength:
  Max: 120
